### ISSUE TITLE
Getting error 500 on new client 

### ISSUE THREAD

**Issue by amirilidan78** [zelenin/go-tdlib#84]
im getting this error do you know how i can fix it ? 
```
2022/09/28 18:26:45 NewClient error: 500 Request aborted
```
[i used the code from quick start ](https://github.com/zelenin/go-tdlib#client)

and replaced my app id and hash

**Comment by McLayer** [comment]
Currently `go-tdlib` doesn't support `tdlib` version > `1.8.4`
So building `tdlib` version `1.8.4` should fix the problem. Just run ```git checkout 7eabd8ca60de025e45e99d4e5edd39f4ebd9467e```  in `tdlib` dir and rebuild it.

**Comment by elboletaire** [comment]
That worked for me, thanks @McLayer

**Comment by Amirilidan78** [comment]
tnx 😍

**Comment by AlexObukhoff** [comment]
Version 1.8.4 is already quite old. 
Who knows how to fix compatibility with the latest 1.8.13?

**Comment by dylanpoe** [comment]
> I fixed it, see #89

Hi,I still got this error, using the   git checkout 7eabd8ca60de025e45e99d4e5edd39f4ebd9467e

And then switch to the latest version  ,still got the error 
git log daf480138d482e7970f6d7a681d778a98f11fdd2
my PC is  ,what should I do ?
I found the error is ,but the api_id is valid ,because I put the id in  https://github.com/TelegramOrg/Telegram-web-k
and it works
<img width="1013" alt="image" src="https://github.com/zelenin/go-tdlib/assets/15873683/2e0ba045-f160-4402-8c39-ce735c75123f">

<img width="257" alt="image" src="https://github.com/zelenin/go-tdlib/assets/15873683/a7e365d8-f07a-4438-9f9e-950d35e2764d">

<img width="555" alt="image" src="https://github.com/zelenin/go-tdlib/assets/15873683/7f308b2d-e985-4504-a5c5-ed1dd3de4016">

**Comment by zelenin** [comment]
use the library only with the latest tagged version. I don't have the ability to test the changes of each commit and fix errors. I only support tagged versions
this is a working example https://github.com/zelenin/go-tdlib/tree/master/example

**Comment by dylanpoe** [comment]
Thank you so much ,I do as the tagged version, v1.8.0 ,so the problems has been  solved

**Comment by FunkyYang** [comment]
I rollback td version as  v1.8.4 and throw this error 
```
GetOption error: 400 The method can't be executed synchronously
```
